import { connect } from './drive.mjs'; import { mkdirSync } from 'node:fs';
const [url, out] = process.argv.slice(2); mkdirSync(out, { recursive: true });
const b = await connect(); const wait = ms => `new Promise(r => setTimeout(r, ${ms}))`;
const p = await b.page(url, { width: 1440, height: 900 });
await p.eval(`new Promise(r => { const st = document.querySelector('.hero__stage'); const t = setInterval(() => { if (st.classList.contains('video-ready') || st.classList.contains('video-failed')) { clearInterval(t); r(); } }, 100); setTimeout(r, 8000); })`);
await p.eval(wait(2400));
const r = await p.eval("(() => { const b = document.querySelector('.band--1 p.hook').getBoundingClientRect(); return { l: b.left, t: b.top, w: b.width, h: b.height, live: document.querySelector('.band--1').classList.contains('is-live') }; })()");
console.log('hook', JSON.stringify(r));
await p.shot(`${out}/lens-rest.png`);
await p.mouse('mouseMoved', r.l + r.w * 0.3, r.t + r.h * 0.28);
await p.eval(wait(700));
await p.shot(`${out}/lens-a.png`);
await p.mouse('mouseMoved', r.l + r.w * 0.55, r.t + r.h * 0.72);
await p.eval(wait(700));
await p.shot(`${out}/lens-b.png`);
console.log('lens', JSON.stringify(await p.eval("(() => { const l = document.querySelector('.lens'); if (!l) return { lens: false }; const cs = getComputedStyle(l); return { on: l.classList.contains('is-on'), opacity: cs.opacity, w: cs.width, h: cs.height, copies: l.querySelectorAll('.lens__copy').length, letters: l.querySelectorAll('.lens__copy .hk').length, filter: getComputedStyle(l.querySelector('.lens__layer--sharp .lens__copy')).filter }; })()")));
await p.mouse('mouseMoved', 1300, 100);
await p.eval(wait(500));
console.log('after leave', JSON.stringify(await p.eval("({ on: document.querySelector('.lens').classList.contains('is-on'), opacity: getComputedStyle(document.querySelector('.lens')).opacity })")), p.errors.length ? p.errors : 'console clean');
await p.close(); b.close();
